sudo: false
language: node_js
node_js:
- '10.16'
script: npm test && npm run build
deploy:
  on:
    branch: master
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
env:
  global:
  - secure: FcvXkCP6u/YxldQ/orK86Rf4uBlqGo/V6VX4FiYlP4CAgzNw3Upf6qwIicLI/4rGYcQIuajf+CdBVjQb9boKduOARNExaq9nuzybzLIOcTQa2oDo2LNHaxuv93+iB3BuTtzHV0rzB2H75U43SP6EwIEvEAnP92Dy+7GMUVTuSYKPpoLsYfLqep+DLSKH0AF4/gDpfTDe51Wj/FvZVl4hZrEqBUtLAvJm6rnXZt7RpPfTxCz7bGwWuCMUxLEaqUWqtrUAfD0bHTBYyYOATPgrYWV2IMV4oaDUGUBmCWTMyf84SBkJ3CI7ASrcV4a4+I3s9j8MkIcNkOAqUdS6dNBVmspGQ0iLaR1Ml4fb68KvsuOp7FOGd6/+hymeOIxKKQIHEhHIQTxayzHpfMzouzEz+LauhY1dJrY+xUUWq35rRcOwFsviW/hAZvKWw8akFronO6AhhHeWevTEHL+rlMWb0EpND8gviPYio7zUfK6vVtqkBLL9qwElpfPWPsGzF14MHxHQt4Q/1sq4V1coiEZsOkjtNV9s4tg4MchAL9Rkf0Yt0Vbb0SSnX+tlX7ZbJmXWklc//QQ0srTWVU/IkVpgAsE3eXUzja+vIhTGE/cEH3cS6nDUm/gUpJ8PzFjE2scs8qatYmeVOsqA5+Roeyo8x7407cxXdq1z9Clt39Y5igY=
  - secure: Fm+LVNeUhyduBkGlThYjm5GQWDnu38uJv5LgqNsuzJ6byyS0v+oNja+LWoYp8ZljuWRQzcGhNPhd4/E6DqjBU5DglS97nCO9hBsU8233pwKJ5B8ob798jYJy9390xYv41lZI/vz4qR59CG9Vihy64PTqe3HNW0Zqjo7pXHKB9I5pXz3fRXwKOW9kSMSlO9Uo4oezT0h+qzOpsXal2OZezxHxrJA2v+Ms3ht9iJUjyiEaFWzlxTQ21Nsi4dpGsD04ZWZoPa4yulHFXy+BDRzfU3gVP5Q2JZoIug8jKfzl19XYJzdF5h1KTzNwNf8T2n3Z78RT5HbWwS/2lVVTPIlCuQx8TO80omX6eSripbT8fKC3da9epf09wvr1+bC05fttYgPEXjCvzKHsjIzLPebH+R5qxUvorn8fqM6/FN6o+8/sTFlVuBVKkGMV2KBc8C5zNvblwGstDk1LH4qTHwN6dhkIIjbLN6mNfOndEA+LNJRf9qWlU2LNhT2tQS36sdwGmBwchW3dUEWAw3yDemNJ3e2ckv2BulD9stkZ+NL2nR7qV/eKkHBp7xtzYi6Oo4DBNri/rqC6Sd4KewxVxb8gFDL7+p5H4l0y4DvDN25w4CUsA5m7UMXV22kq/za+dtadE9R9zHqshVT91kG5q6DHa04UYvH9/mn1gmjW5xaeyig=
